sudo: false

branches:
  only:
    - dev

language: ruby

cache: bundler

rvm:
- 2.2.3

install:
  - bundle install

script:
  - ./scripts/build.sh

exclude: [vendor]

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
