#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/neildmorris/neildmorris.github.io.git --branch master

# build with Jekyll into "_site"
bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external

# push
cd _site
git config user.email "neil.daren.morris@gamil.com"
git config user.name "Neil D. Morris"
git add --all
git commit -a -m "TRAVIS #$TRAVIS_BUILD_NUMBER"
git push --force origin master
